name: Build Test Workflow
on:
  pull_request:
    branches:
      - main
jobs:
  Build:
    name: Build test
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Docker Compose
        run: docker compose up -d
      - name: Verify Docker Compose
        run: |
          if docker-compose ps | grep 'Exit'; then
            echo 'A Docker container did NOT start successfully';
            exit 1;
          fi
